// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/JailtonJunior94/devkit-go/pkg/observability"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetrics creates a new instance of MockMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetrics {
	mock := &MockMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetrics is an autogenerated mock type for the Metrics type
type MockMetrics struct {
	mock.Mock
}

type MockMetrics_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetrics) EXPECT() *MockMetrics_Expecter {
	return &MockMetrics_Expecter{mock: &_m.Mock}
}

// Counter provides a mock function for the type MockMetrics
func (_mock *MockMetrics) Counter(name string, description string, unit string) observability.Counter {
	ret := _mock.Called(name, description, unit)

	if len(ret) == 0 {
		panic("no return value specified for Counter")
	}

	var r0 observability.Counter
	if returnFunc, ok := ret.Get(0).(func(string, string, string) observability.Counter); ok {
		r0 = returnFunc(name, description, unit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(observability.Counter)
		}
	}
	return r0
}

// MockMetrics_Counter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Counter'
type MockMetrics_Counter_Call struct {
	*mock.Call
}

// Counter is a helper method to define mock.On call
//   - name string
//   - description string
//   - unit string
func (_e *MockMetrics_Expecter) Counter(name interface{}, description interface{}, unit interface{}) *MockMetrics_Counter_Call {
	return &MockMetrics_Counter_Call{Call: _e.mock.On("Counter", name, description, unit)}
}

func (_c *MockMetrics_Counter_Call) Run(run func(name string, description string, unit string)) *MockMetrics_Counter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetrics_Counter_Call) Return(counter observability.Counter) *MockMetrics_Counter_Call {
	_c.Call.Return(counter)
	return _c
}

func (_c *MockMetrics_Counter_Call) RunAndReturn(run func(name string, description string, unit string) observability.Counter) *MockMetrics_Counter_Call {
	_c.Call.Return(run)
	return _c
}

// Gauge provides a mock function for the type MockMetrics
func (_mock *MockMetrics) Gauge(name string, description string, unit string, callback observability.GaugeCallback) error {
	ret := _mock.Called(name, description, unit, callback)

	if len(ret) == 0 {
		panic("no return value specified for Gauge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, observability.GaugeCallback) error); ok {
		r0 = returnFunc(name, description, unit, callback)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetrics_Gauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Gauge'
type MockMetrics_Gauge_Call struct {
	*mock.Call
}

// Gauge is a helper method to define mock.On call
//   - name string
//   - description string
//   - unit string
//   - callback observability.GaugeCallback
func (_e *MockMetrics_Expecter) Gauge(name interface{}, description interface{}, unit interface{}, callback interface{}) *MockMetrics_Gauge_Call {
	return &MockMetrics_Gauge_Call{Call: _e.mock.On("Gauge", name, description, unit, callback)}
}

func (_c *MockMetrics_Gauge_Call) Run(run func(name string, description string, unit string, callback observability.GaugeCallback)) *MockMetrics_Gauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 observability.GaugeCallback
		if args[3] != nil {
			arg3 = args[3].(observability.GaugeCallback)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMetrics_Gauge_Call) Return(err error) *MockMetrics_Gauge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetrics_Gauge_Call) RunAndReturn(run func(name string, description string, unit string, callback observability.GaugeCallback) error) *MockMetrics_Gauge_Call {
	_c.Call.Return(run)
	return _c
}

// Histogram provides a mock function for the type MockMetrics
func (_mock *MockMetrics) Histogram(name string, description string, unit string) observability.Histogram {
	ret := _mock.Called(name, description, unit)

	if len(ret) == 0 {
		panic("no return value specified for Histogram")
	}

	var r0 observability.Histogram
	if returnFunc, ok := ret.Get(0).(func(string, string, string) observability.Histogram); ok {
		r0 = returnFunc(name, description, unit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(observability.Histogram)
		}
	}
	return r0
}

// MockMetrics_Histogram_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Histogram'
type MockMetrics_Histogram_Call struct {
	*mock.Call
}

// Histogram is a helper method to define mock.On call
//   - name string
//   - description string
//   - unit string
func (_e *MockMetrics_Expecter) Histogram(name interface{}, description interface{}, unit interface{}) *MockMetrics_Histogram_Call {
	return &MockMetrics_Histogram_Call{Call: _e.mock.On("Histogram", name, description, unit)}
}

func (_c *MockMetrics_Histogram_Call) Run(run func(name string, description string, unit string)) *MockMetrics_Histogram_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetrics_Histogram_Call) Return(histogram observability.Histogram) *MockMetrics_Histogram_Call {
	_c.Call.Return(histogram)
	return _c
}

func (_c *MockMetrics_Histogram_Call) RunAndReturn(run func(name string, description string, unit string) observability.Histogram) *MockMetrics_Histogram_Call {
	_c.Call.Return(run)
	return _c
}

// HistogramWithBuckets provides a mock function for the type MockMetrics
func (_mock *MockMetrics) HistogramWithBuckets(name string, description string, unit string, buckets []float64) observability.Histogram {
	ret := _mock.Called(name, description, unit, buckets)

	if len(ret) == 0 {
		panic("no return value specified for HistogramWithBuckets")
	}

	var r0 observability.Histogram
	if returnFunc, ok := ret.Get(0).(func(string, string, string, []float64) observability.Histogram); ok {
		r0 = returnFunc(name, description, unit, buckets)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(observability.Histogram)
		}
	}
	return r0
}

// MockMetrics_HistogramWithBuckets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HistogramWithBuckets'
type MockMetrics_HistogramWithBuckets_Call struct {
	*mock.Call
}

// HistogramWithBuckets is a helper method to define mock.On call
//   - name string
//   - description string
//   - unit string
//   - buckets []float64
func (_e *MockMetrics_Expecter) HistogramWithBuckets(name interface{}, description interface{}, unit interface{}, buckets interface{}) *MockMetrics_HistogramWithBuckets_Call {
	return &MockMetrics_HistogramWithBuckets_Call{Call: _e.mock.On("HistogramWithBuckets", name, description, unit, buckets)}
}

func (_c *MockMetrics_HistogramWithBuckets_Call) Run(run func(name string, description string, unit string, buckets []float64)) *MockMetrics_HistogramWithBuckets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []float64
		if args[3] != nil {
			arg3 = args[3].([]float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMetrics_HistogramWithBuckets_Call) Return(histogram observability.Histogram) *MockMetrics_HistogramWithBuckets_Call {
	_c.Call.Return(histogram)
	return _c
}

func (_c *MockMetrics_HistogramWithBuckets_Call) RunAndReturn(run func(name string, description string, unit string, buckets []float64) observability.Histogram) *MockMetrics_HistogramWithBuckets_Call {
	_c.Call.Return(run)
	return _c
}

// UpDownCounter provides a mock function for the type MockMetrics
func (_mock *MockMetrics) UpDownCounter(name string, description string, unit string) observability.UpDownCounter {
	ret := _mock.Called(name, description, unit)

	if len(ret) == 0 {
		panic("no return value specified for UpDownCounter")
	}

	var r0 observability.UpDownCounter
	if returnFunc, ok := ret.Get(0).(func(string, string, string) observability.UpDownCounter); ok {
		r0 = returnFunc(name, description, unit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(observability.UpDownCounter)
		}
	}
	return r0
}

// MockMetrics_UpDownCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpDownCounter'
type MockMetrics_UpDownCounter_Call struct {
	*mock.Call
}

// UpDownCounter is a helper method to define mock.On call
//   - name string
//   - description string
//   - unit string
func (_e *MockMetrics_Expecter) UpDownCounter(name interface{}, description interface{}, unit interface{}) *MockMetrics_UpDownCounter_Call {
	return &MockMetrics_UpDownCounter_Call{Call: _e.mock.On("UpDownCounter", name, description, unit)}
}

func (_c *MockMetrics_UpDownCounter_Call) Run(run func(name string, description string, unit string)) *MockMetrics_UpDownCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetrics_UpDownCounter_Call) Return(upDownCounter observability.UpDownCounter) *MockMetrics_UpDownCounter_Call {
	_c.Call.Return(upDownCounter)
	return _c
}

func (_c *MockMetrics_UpDownCounter_Call) RunAndReturn(run func(name string, description string, unit string) observability.UpDownCounter) *MockMetrics_UpDownCounter_Call {
	_c.Call.Return(run)
	return _c
}
