// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/JailtonJunior94/devkit-go/pkg/observability"
	mock "github.com/stretchr/testify/mock"
)

// NewMockObservability creates a new instance of MockObservability. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObservability(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObservability {
	mock := &MockObservability{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObservability is an autogenerated mock type for the Observability type
type MockObservability struct {
	mock.Mock
}

type MockObservability_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObservability) EXPECT() *MockObservability_Expecter {
	return &MockObservability_Expecter{mock: &_m.Mock}
}

// Logger provides a mock function for the type MockObservability
func (_mock *MockObservability) Logger() observability.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 observability.Logger
	if returnFunc, ok := ret.Get(0).(func() observability.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(observability.Logger)
		}
	}
	return r0
}

// MockObservability_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockObservability_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockObservability_Expecter) Logger() *MockObservability_Logger_Call {
	return &MockObservability_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockObservability_Logger_Call) Run(run func()) *MockObservability_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockObservability_Logger_Call) Return(logger observability.Logger) *MockObservability_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockObservability_Logger_Call) RunAndReturn(run func() observability.Logger) *MockObservability_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// Metrics provides a mock function for the type MockObservability
func (_mock *MockObservability) Metrics() observability.Metrics {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metrics")
	}

	var r0 observability.Metrics
	if returnFunc, ok := ret.Get(0).(func() observability.Metrics); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(observability.Metrics)
		}
	}
	return r0
}

// MockObservability_Metrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metrics'
type MockObservability_Metrics_Call struct {
	*mock.Call
}

// Metrics is a helper method to define mock.On call
func (_e *MockObservability_Expecter) Metrics() *MockObservability_Metrics_Call {
	return &MockObservability_Metrics_Call{Call: _e.mock.On("Metrics")}
}

func (_c *MockObservability_Metrics_Call) Run(run func()) *MockObservability_Metrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockObservability_Metrics_Call) Return(metrics observability.Metrics) *MockObservability_Metrics_Call {
	_c.Call.Return(metrics)
	return _c
}

func (_c *MockObservability_Metrics_Call) RunAndReturn(run func() observability.Metrics) *MockObservability_Metrics_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockObservability
func (_mock *MockObservability) Shutdown(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObservability_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockObservability_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockObservability_Expecter) Shutdown(ctx interface{}) *MockObservability_Shutdown_Call {
	return &MockObservability_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockObservability_Shutdown_Call) Run(run func(ctx context.Context)) *MockObservability_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObservability_Shutdown_Call) Return(err error) *MockObservability_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObservability_Shutdown_Call) RunAndReturn(run func(ctx context.Context) error) *MockObservability_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// Tracer provides a mock function for the type MockObservability
func (_mock *MockObservability) Tracer() observability.Tracer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tracer")
	}

	var r0 observability.Tracer
	if returnFunc, ok := ret.Get(0).(func() observability.Tracer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(observability.Tracer)
		}
	}
	return r0
}

// MockObservability_Tracer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tracer'
type MockObservability_Tracer_Call struct {
	*mock.Call
}

// Tracer is a helper method to define mock.On call
func (_e *MockObservability_Expecter) Tracer() *MockObservability_Tracer_Call {
	return &MockObservability_Tracer_Call{Call: _e.mock.On("Tracer")}
}

func (_c *MockObservability_Tracer_Call) Run(run func()) *MockObservability_Tracer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockObservability_Tracer_Call) Return(tracer observability.Tracer) *MockObservability_Tracer_Call {
	_c.Call.Return(tracer)
	return _c
}

func (_c *MockObservability_Tracer_Call) RunAndReturn(run func() observability.Tracer) *MockObservability_Tracer_Call {
	_c.Call.Return(run)
	return _c
}
