// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/JailtonJunior94/devkit-go/pkg/observability"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTracer creates a new instance of MockTracer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTracer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTracer {
	mock := &MockTracer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTracer is an autogenerated mock type for the Tracer type
type MockTracer struct {
	mock.Mock
}

type MockTracer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTracer) EXPECT() *MockTracer_Expecter {
	return &MockTracer_Expecter{mock: &_m.Mock}
}

// ContextWithSpan provides a mock function for the type MockTracer
func (_mock *MockTracer) ContextWithSpan(ctx context.Context, span observability.Span) context.Context {
	ret := _mock.Called(ctx, span)

	if len(ret) == 0 {
		panic("no return value specified for ContextWithSpan")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func(context.Context, observability.Span) context.Context); ok {
		r0 = returnFunc(ctx, span)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockTracer_ContextWithSpan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContextWithSpan'
type MockTracer_ContextWithSpan_Call struct {
	*mock.Call
}

// ContextWithSpan is a helper method to define mock.On call
//   - ctx context.Context
//   - span observability.Span
func (_e *MockTracer_Expecter) ContextWithSpan(ctx interface{}, span interface{}) *MockTracer_ContextWithSpan_Call {
	return &MockTracer_ContextWithSpan_Call{Call: _e.mock.On("ContextWithSpan", ctx, span)}
}

func (_c *MockTracer_ContextWithSpan_Call) Run(run func(ctx context.Context, span observability.Span)) *MockTracer_ContextWithSpan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 observability.Span
		if args[1] != nil {
			arg1 = args[1].(observability.Span)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTracer_ContextWithSpan_Call) Return(context1 context.Context) *MockTracer_ContextWithSpan_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockTracer_ContextWithSpan_Call) RunAndReturn(run func(ctx context.Context, span observability.Span) context.Context) *MockTracer_ContextWithSpan_Call {
	_c.Call.Return(run)
	return _c
}

// SpanFromContext provides a mock function for the type MockTracer
func (_mock *MockTracer) SpanFromContext(ctx context.Context) observability.Span {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SpanFromContext")
	}

	var r0 observability.Span
	if returnFunc, ok := ret.Get(0).(func(context.Context) observability.Span); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(observability.Span)
		}
	}
	return r0
}

// MockTracer_SpanFromContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SpanFromContext'
type MockTracer_SpanFromContext_Call struct {
	*mock.Call
}

// SpanFromContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTracer_Expecter) SpanFromContext(ctx interface{}) *MockTracer_SpanFromContext_Call {
	return &MockTracer_SpanFromContext_Call{Call: _e.mock.On("SpanFromContext", ctx)}
}

func (_c *MockTracer_SpanFromContext_Call) Run(run func(ctx context.Context)) *MockTracer_SpanFromContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTracer_SpanFromContext_Call) Return(span observability.Span) *MockTracer_SpanFromContext_Call {
	_c.Call.Return(span)
	return _c
}

func (_c *MockTracer_SpanFromContext_Call) RunAndReturn(run func(ctx context.Context) observability.Span) *MockTracer_SpanFromContext_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockTracer
func (_mock *MockTracer) Start(ctx context.Context, spanName string, opts ...observability.SpanOption) (context.Context, observability.Span) {
	// observability.SpanOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, spanName)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 context.Context
	var r1 observability.Span
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...observability.SpanOption) (context.Context, observability.Span)); ok {
		return returnFunc(ctx, spanName, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...observability.SpanOption) context.Context); ok {
		r0 = returnFunc(ctx, spanName, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...observability.SpanOption) observability.Span); ok {
		r1 = returnFunc(ctx, spanName, opts...)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(observability.Span)
		}
	}
	return r0, r1
}

// MockTracer_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockTracer_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - spanName string
//   - opts ...observability.SpanOption
func (_e *MockTracer_Expecter) Start(ctx interface{}, spanName interface{}, opts ...interface{}) *MockTracer_Start_Call {
	return &MockTracer_Start_Call{Call: _e.mock.On("Start",
		append([]interface{}{ctx, spanName}, opts...)...)}
}

func (_c *MockTracer_Start_Call) Run(run func(ctx context.Context, spanName string, opts ...observability.SpanOption)) *MockTracer_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []observability.SpanOption
		variadicArgs := make([]observability.SpanOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(observability.SpanOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockTracer_Start_Call) Return(context1 context.Context, span observability.Span) *MockTracer_Start_Call {
	_c.Call.Return(context1, span)
	return _c
}

func (_c *MockTracer_Start_Call) RunAndReturn(run func(ctx context.Context, spanName string, opts ...observability.SpanOption) (context.Context, observability.Span)) *MockTracer_Start_Call {
	_c.Call.Return(run)
	return _c
}
