version: "2"

run:
  timeout: 10m
  concurrency: 5
  verbose: true

issues:
  exclude-dirs:
  - mocks
  exclude-files:
  - vendor
  exclude-rules:
  - path: _test\.go
    linters:
    - errcheck
    - gosec

linters:
  disable:
  - godox
  enable-all: false
  enable:
  - bodyclose
  - gochecknoinits
  - gocritic
  - errcheck
  - godot
  - govet
  - gosec
  - gocyclo
  - ineffassign
  - staticcheck
