template: testify
template-data:
  unroll-variadic: true
dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName | snakecase}}.go"
pkgname: "mocks"
packages:
  github.com/JailtonJunior94/devkit-go/pkg/observability:
    interfaces:
      Observability:
      Tracer:
      Logger:
      Metrics:
