template: testify
template-data:
  unroll-variadic: true
dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName | snakecase}}.go"
pkgname: "mocks"
packages:
  github.com/JailtonJunior94/devkit-go/pkg/observability:
    interfaces:
      Observability:
      Tracer:
      Logger:
      Metrics:
  github.com/JailtonJunior94/devkit-go/pkg/database:
    interfaces:
      DBTX:
      Result:
      Rows:
      Row:
  github.com/JailtonJunior94/devkit-go/pkg/database/manager:
    interfaces:
      Manager:
      DriverConfig:
  github.com/JailtonJunior94/devkit-go/pkg/database/migration:
    interfaces:
      Migrator:
      Source:
