// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/go-chi/chi/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRouter creates a new instance of MockRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRouter {
	mock := &MockRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRouter is an autogenerated mock type for the Router type
type MockRouter struct {
	mock.Mock
}

type MockRouter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRouter) EXPECT() *MockRouter_Expecter {
	return &MockRouter_Expecter{mock: &_m.Mock}
}

// Register provides a mock function for the type MockRouter
func (_mock *MockRouter) Register(router chi.Router) {
	_mock.Called(router)
	return
}

// MockRouter_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockRouter_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - router chi.Router
func (_e *MockRouter_Expecter) Register(router interface{}) *MockRouter_Register_Call {
	return &MockRouter_Register_Call{Call: _e.mock.On("Register", router)}
}

func (_c *MockRouter_Register_Call) Run(run func(router chi.Router)) *MockRouter_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 chi.Router
		if args[0] != nil {
			arg0 = args[0].(chi.Router)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRouter_Register_Call) Return() *MockRouter_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRouter_Register_Call) RunAndReturn(run func(router chi.Router)) *MockRouter_Register_Call {
	_c.Run(run)
	return _c
}
