// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMigrator creates a new instance of MockMigrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMigrator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMigrator {
	mock := &MockMigrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMigrator is an autogenerated mock type for the Migrator type
type MockMigrator struct {
	mock.Mock
}

type MockMigrator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMigrator) EXPECT() *MockMigrator_Expecter {
	return &MockMigrator_Expecter{mock: &_m.Mock}
}

// Down provides a mock function for the type MockMigrator
func (_mock *MockMigrator) Down(ctx context.Context, steps int) error {
	ret := _mock.Called(ctx, steps)

	if len(ret) == 0 {
		panic("no return value specified for Down")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, steps)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMigrator_Down_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Down'
type MockMigrator_Down_Call struct {
	*mock.Call
}

// Down is a helper method to define mock.On call
//   - ctx context.Context
//   - steps int
func (_e *MockMigrator_Expecter) Down(ctx interface{}, steps interface{}) *MockMigrator_Down_Call {
	return &MockMigrator_Down_Call{Call: _e.mock.On("Down", ctx, steps)}
}

func (_c *MockMigrator_Down_Call) Run(run func(ctx context.Context, steps int)) *MockMigrator_Down_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMigrator_Down_Call) Return(err error) *MockMigrator_Down_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMigrator_Down_Call) RunAndReturn(run func(ctx context.Context, steps int) error) *MockMigrator_Down_Call {
	_c.Call.Return(run)
	return _c
}

// Force provides a mock function for the type MockMigrator
func (_mock *MockMigrator) Force(ctx context.Context, version int) error {
	ret := _mock.Called(ctx, version)

	if len(ret) == 0 {
		panic("no return value specified for Force")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, version)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMigrator_Force_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Force'
type MockMigrator_Force_Call struct {
	*mock.Call
}

// Force is a helper method to define mock.On call
//   - ctx context.Context
//   - version int
func (_e *MockMigrator_Expecter) Force(ctx interface{}, version interface{}) *MockMigrator_Force_Call {
	return &MockMigrator_Force_Call{Call: _e.mock.On("Force", ctx, version)}
}

func (_c *MockMigrator_Force_Call) Run(run func(ctx context.Context, version int)) *MockMigrator_Force_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMigrator_Force_Call) Return(err error) *MockMigrator_Force_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMigrator_Force_Call) RunAndReturn(run func(ctx context.Context, version int) error) *MockMigrator_Force_Call {
	_c.Call.Return(run)
	return _c
}

// Up provides a mock function for the type MockMigrator
func (_mock *MockMigrator) Up(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Up")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMigrator_Up_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Up'
type MockMigrator_Up_Call struct {
	*mock.Call
}

// Up is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMigrator_Expecter) Up(ctx interface{}) *MockMigrator_Up_Call {
	return &MockMigrator_Up_Call{Call: _e.mock.On("Up", ctx)}
}

func (_c *MockMigrator_Up_Call) Run(run func(ctx context.Context)) *MockMigrator_Up_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMigrator_Up_Call) Return(err error) *MockMigrator_Up_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMigrator_Up_Call) RunAndReturn(run func(ctx context.Context) error) *MockMigrator_Up_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function for the type MockMigrator
func (_mock *MockMigrator) Version(ctx context.Context) (uint, bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 uint
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (uint, bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) uint); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(uint)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) bool); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(ctx)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockMigrator_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockMigrator_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMigrator_Expecter) Version(ctx interface{}) *MockMigrator_Version_Call {
	return &MockMigrator_Version_Call{Call: _e.mock.On("Version", ctx)}
}

func (_c *MockMigrator_Version_Call) Run(run func(ctx context.Context)) *MockMigrator_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMigrator_Version_Call) Return(version uint, dirty bool, err error) *MockMigrator_Version_Call {
	_c.Call.Return(version, dirty, err)
	return _c
}

func (_c *MockMigrator_Version_Call) RunAndReturn(run func(ctx context.Context) (uint, bool, error)) *MockMigrator_Version_Call {
	_c.Call.Return(run)
	return _c
}
