// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSource creates a new instance of MockSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSource {
	mock := &MockSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSource is an autogenerated mock type for the Source type
type MockSource struct {
	mock.Mock
}

type MockSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSource) EXPECT() *MockSource_Expecter {
	return &MockSource_Expecter{mock: &_m.Mock}
}

// sourceMarker provides a mock function for the type MockSource
func (_mock *MockSource) sourceMarker() {
	_mock.Called()
	return
}

// MockSource_sourceMarker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'sourceMarker'
type MockSource_sourceMarker_Call struct {
	*mock.Call
}

// sourceMarker is a helper method to define mock.On call
func (_e *MockSource_Expecter) sourceMarker() *MockSource_sourceMarker_Call {
	return &MockSource_sourceMarker_Call{Call: _e.mock.On("sourceMarker")}
}

func (_c *MockSource_sourceMarker_Call) Run(run func()) *MockSource_sourceMarker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSource_sourceMarker_Call) Return() *MockSource_sourceMarker_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSource_sourceMarker_Call) RunAndReturn(run func()) *MockSource_sourceMarker_Call {
	_c.Run(run)
	return _c
}
