// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/JailtonJunior94/devkit-go/pkg/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function for the type MockManager
func (_mock *MockManager) BeginTx(ctx context.Context, opts database.TxOptions) (database.Tx, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 database.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.TxOptions) (database.Tx, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, database.TxOptions) database.Tx); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, database.TxOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManager_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockManager_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - opts database.TxOptions
func (_e *MockManager_Expecter) BeginTx(ctx interface{}, opts interface{}) *MockManager_BeginTx_Call {
	return &MockManager_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, opts)}
}

func (_c *MockManager_BeginTx_Call) Run(run func(ctx context.Context, opts database.TxOptions)) *MockManager_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 database.TxOptions
		if args[1] != nil {
			arg1 = args[1].(database.TxOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManager_BeginTx_Call) Return(tx database.Tx, err error) *MockManager_BeginTx_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *MockManager_BeginTx_Call) RunAndReturn(run func(ctx context.Context, opts database.TxOptions) (database.Tx, error)) *MockManager_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// DBTX provides a mock function for the type MockManager
func (_mock *MockManager) DBTX(ctx context.Context) database.DBTX {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DBTX")
	}

	var r0 database.DBTX
	if returnFunc, ok := ret.Get(0).(func(context.Context) database.DBTX); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.DBTX)
		}
	}
	return r0
}

// MockManager_DBTX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DBTX'
type MockManager_DBTX_Call struct {
	*mock.Call
}

// DBTX is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManager_Expecter) DBTX(ctx interface{}) *MockManager_DBTX_Call {
	return &MockManager_DBTX_Call{Call: _e.mock.On("DBTX", ctx)}
}

func (_c *MockManager_DBTX_Call) Run(run func(ctx context.Context)) *MockManager_DBTX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_DBTX_Call) Return(dBTX database.DBTX) *MockManager_DBTX_Call {
	_c.Call.Return(dBTX)
	return _c
}

func (_c *MockManager_DBTX_Call) RunAndReturn(run func(ctx context.Context) database.DBTX) *MockManager_DBTX_Call {
	_c.Call.Return(run)
	return _c
}

// Driver provides a mock function for the type MockManager
func (_mock *MockManager) Driver() database.Driver {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Driver")
	}

	var r0 database.Driver
	if returnFunc, ok := ret.Get(0).(func() database.Driver); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(database.Driver)
	}
	return r0
}

// MockManager_Driver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Driver'
type MockManager_Driver_Call struct {
	*mock.Call
}

// Driver is a helper method to define mock.On call
func (_e *MockManager_Expecter) Driver() *MockManager_Driver_Call {
	return &MockManager_Driver_Call{Call: _e.mock.On("Driver")}
}

func (_c *MockManager_Driver_Call) Run(run func()) *MockManager_Driver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_Driver_Call) Return(driver database.Driver) *MockManager_Driver_Call {
	_c.Call.Return(driver)
	return _c
}

func (_c *MockManager_Driver_Call) RunAndReturn(run func() database.Driver) *MockManager_Driver_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockManager
func (_mock *MockManager) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockManager_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManager_Expecter) Ping(ctx interface{}) *MockManager_Ping_Call {
	return &MockManager_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockManager_Ping_Call) Run(run func(ctx context.Context)) *MockManager_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_Ping_Call) Return(err error) *MockManager_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockManager_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockManager
func (_mock *MockManager) Shutdown(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManager_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockManager_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManager_Expecter) Shutdown(ctx interface{}) *MockManager_Shutdown_Call {
	return &MockManager_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockManager_Shutdown_Call) Run(run func(ctx context.Context)) *MockManager_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockManager_Shutdown_Call) Return(err error) *MockManager_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManager_Shutdown_Call) RunAndReturn(run func(ctx context.Context) error) *MockManager_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}
