name: Continuos Integration
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Lint
    runs-on: self-hosted
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: false
      - uses: actions/checkout@v4
      - name: Lint
        run: make lint

  test:
    name: Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: false
      - name: Test
        run: make test
