name: Continuos Integration
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  continuos-integration:
    name: Continuos Integration
    runs-on: ubuntu-latest
    steps:
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
          cache: false

      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: go test -json -race ./... -covermode=atomic -coverprofile devkit_go-tests.out
